"""ag_core/collab_log.py — deterministic AI-collaboration-log exporter.

Pure fixture-built workspaces: no pipeline, no env gates, no mocks. The
exporter must be a pure function of the workspace tree (contents + mtimes)
and never raise on missing inputs.
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from ag_core.collab_log import (  # noqa: E402
    _review_section,
    export_collab_log,
    main,
    refresh_log_if_present,
)

_JOB_ID = "a" * 32
_T0 = 1780000000.0  # fixed epoch base so mtimes are deterministic


def _write(path, text, mtime=None):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    if mtime is not None:
        os.utime(path, (mtime, mtime))


def _build_workspace(tmp_path, with_manifest=True):
    ws = str(tmp_path)
    if with_manifest:
        _write(
            os.path.join(ws, "job.json"),
            json.dumps(
                {
                    "job_id": _JOB_ID,
                    "status": "completed",
                    "pipeline": "custom",
                    "prompt": "Build a demo | with a pipe\nand a newline",
                    "workspace": ws,
                    "started_at": _T0,
                    "finished_at": _T0 + 3600,
                }
            ),
        )
    raw = os.path.join(ws, ".genius", "slug", "logs", "raw")
    _write(os.path.join(raw, "design_retry1.md"), "d" * 10, mtime=_T0 + 10)
    _write(os.path.join(raw, "codex_foo_attempt1.md"), "c" * 20, mtime=_T0 + 20)
    _write(os.path.join(raw, "tester_foo_attempt1.md"), "t" * 30, mtime=_T0 + 30)
    _write(os.path.join(raw, "security_foo_attempt2.md"), "s" * 40, mtime=_T0 + 40)
    _write(os.path.join(raw, "final_review.md"), "f" * 50, mtime=_T0 + 50)
    _write(os.path.join(raw, "pitch.md"), "p" * 60, mtime=_T0 + 60)
    _write(
        os.path.join(ws, "review.md"),
        "# Review\n\nbody\n\n"
        "## Verification coverage\n"
        "- foo.py: generated pytest module executed\n\n"
        "## File quality states\n"
        "- foo.py: tested, security-accepted\n\n"
        "## Release readiness\n"
        "release-ready: YES\n",
    )
    return ws


def test_export_full_workspace(tmp_path):
    ws = _build_workspace(tmp_path)
    out = export_collab_log(ws)

    # Job table values (pipe in the prompt must be escaped, newline collapsed).
    assert f"| Job ID | {_JOB_ID} |" in out
    assert "| Status | completed |" in out
    assert "| Pipeline | custom |" in out
    assert "Build a demo \\| with a pipe and a newline" in out

    # Timeline rows in mtime order with parsed stage labels.
    rows = [ln for ln in out.splitlines() if ln.startswith("| ") and ".md |" in ln]
    assert len(rows) == 6
    assert "design (format retry)" in rows[0]
    assert "| code | foo | 1 | codex_foo_attempt1.md | 20 |" in rows[1]
    assert "| test-generation | foo | 1 |" in rows[2]
    assert "| security-audit | foo | 2 |" in rows[3]
    assert "| final review |" in rows[4]
    assert "| pitch generation |" in rows[5]

    # review.md sections copied verbatim; Release readiness NOT swallowed.
    assert "- foo.py: generated pytest module executed" in out
    assert "- foo.py: tested, security-accepted" in out
    assert "release-ready: YES" not in out

    # Provenance carries both manifest timestamps.
    assert "generated by AI agents" in out
    assert "2026-" in out  # formatted UTC timestamps present


def test_export_without_manifest(tmp_path):
    ws = _build_workspace(tmp_path, with_manifest=False)
    out = export_collab_log(ws)
    assert "(not recorded" in out
    # Window falls back to min/max trace mtimes (still a real window).
    assert "during an unrecorded window" not in out
    assert "between " in out


def test_export_empty_workspace(tmp_path):
    out = export_collab_log(str(tmp_path))
    assert "# AI Collaboration Log" in out
    assert "(no raw traces found under .genius/<slug>/logs/raw/)" in out
    assert "(review.md not found)" in out
    assert "during an unrecorded window" in out


def test_export_is_deterministic(tmp_path):
    ws = _build_workspace(tmp_path)
    assert export_collab_log(ws) == export_collab_log(ws)


def test_flat_name_with_underscores(tmp_path):
    ws = str(tmp_path)
    raw = os.path.join(ws, ".genius", "slug", "logs", "raw")
    _write(os.path.join(raw, "codex_src_pkg_util_attempt3.md"), "x", mtime=_T0)
    out = export_collab_log(ws)
    assert "| code | src_pkg_util | 3 | codex_src_pkg_util_attempt3.md |" in out


def test_cli_main(tmp_path, capsys):
    ws = _build_workspace(tmp_path)

    assert main([ws]) == 0
    captured = capsys.readouterr()
    assert captured.out == export_collab_log(ws) + "\n"

    assert main([]) == 2
    assert "usage:" in capsys.readouterr().err

    out_file = str(tmp_path / "log.md")
    assert main([ws, "--out", out_file]) == 0
    with open(out_file, "r", encoding="utf-8") as fh:
        assert fh.read() == export_collab_log(ws)


def test_refresh_log_if_present(tmp_path):
    ws = _build_workspace(tmp_path)
    # Absent -> False, and the file is NOT created.
    assert refresh_log_if_present(ws) is False
    assert not os.path.exists(os.path.join(ws, "ai_collaboration_log.md"))
    # Present (stale content) -> True, rewritten with the real export.
    log_path = os.path.join(ws, "ai_collaboration_log.md")
    _write(log_path, "STALE")
    assert refresh_log_if_present(ws) is True
    with open(log_path, encoding="utf-8") as fh:
        assert fh.read() == export_collab_log(ws)


def test_review_section_extraction_stops_at_next_heading():
    text = (
        "## Verification coverage\nline1\n### nested\nline2\n\n"
        "## File quality states\nstates\n"
    )
    body = _review_section(text, "Verification coverage")
    assert body == "line1\n### nested\nline2"
    assert _review_section(text, "File quality states") == "states"
    assert _review_section(text, "Missing") is None
