import os
import re
import asyncio
import atexit
import logging
import shutil
import stat
import tempfile
import threading
from typing import List, Optional, Union
from ag_core.config import load_config
from ag_core.utils.cli_runner import (
    communicate_with_timeout,
    cli_timeout,
    CLITimeoutError,
)

logger = logging.getLogger("ag_core.utils.git")


class GitError(Exception):
    """Exception raised for errors in Git operations."""


# --- GIT_ASKPASS credential bridge ------------------------------------------
# Credentials used to be spliced into the remote URL on the git command line
# (https://user:token@host/...), which leaks the token to anything that can
# read process argv (`ps`, /proc, crash reporters). Instead git is pointed at
# a tiny generated askpass script and the values travel in the subprocess's
# OWN environment, which the OS restricts to the process owner. The script
# contains NO secrets — only references to those env vars.
#
# One POSIX sh script covers every supported platform: macOS/Linux execute it
# directly (shebang + 0o700), and git-for-Windows invokes GIT_ASKPASS through
# its bundled sh, which does not need an exec bit.
_ASKPASS_SCRIPT = """#!/bin/sh
# Generated by Genius (ag_core/utils/git.py). Contains no secrets.
case "$1" in
*[Uu]sername*) printf '%s\\n' "$GENIUS_GIT_ASKPASS_USERNAME" ;;
*) printf '%s\\n' "$GENIUS_GIT_ASKPASS_PASSWORD" ;;
esac
"""

_ASKPASS_LOCK = threading.Lock()
_ASKPASS_PATH: Optional[str] = None


def _ensure_askpass_script() -> str:
    """Write the shared askpass helper once per process and return its path."""
    global _ASKPASS_PATH
    with _ASKPASS_LOCK:
        if _ASKPASS_PATH and os.path.isfile(_ASKPASS_PATH):
            return _ASKPASS_PATH
        script_dir = tempfile.mkdtemp(prefix="genius-git-askpass-")
        atexit.register(shutil.rmtree, script_dir, ignore_errors=True)
        path = os.path.join(script_dir, "askpass.sh")
        # newline="\n": git-for-Windows' sh rejects CRLF line endings.
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(_ASKPASS_SCRIPT)
        os.chmod(path, stat.S_IRWXU)
        _ASKPASS_PATH = path
        return path


class GitManager:
    def __init__(self, username: Optional[str] = None, token: Optional[str] = None):
        try:
            config = load_config()
            self.username = (
                username or config.git_username or os.getenv("GIT_USERNAME", "")
            )
            self.token = token or config.git_token or os.getenv("GIT_TOKEN", "")
        except Exception:
            self.username = username or os.getenv("GIT_USERNAME", "")
            self.token = token or os.getenv("GIT_TOKEN", "")

    def _mask(self, text: str) -> str:
        if not text:
            return text
        # Mask URL basic auth: https://user:pass@domain -> https://***:***@domain
        text = re.sub(r"(https?://)[^/:]+:[^/@]+@", r"\1***:***@", text)
        # Mask URL token auth: https://token@domain -> https://***@domain
        text = re.sub(r"(https?://)[^/:@]+@", r"\1***@", text)
        if self.token:
            text = text.replace(self.token, "***")
        return text

    # git's transport-helper syntax `<helper>::<address>` (ext::, fd::, ...)
    # executes commands / reads arbitrary descriptors — never a legitimate
    # remote here. Plain paths, file://, https://, ssh:// and scp-like
    # user@host:path remotes all stay allowed (local-path clones are a
    # supported case).
    _HELPER_URL_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9+.-]*::")

    def _validate_remote_url(self, url: str) -> str:
        """Refuse remote URLs that could smuggle git options or transport
        helpers. Remotes read back from repo config are attacker-influenced
        when operating on cloned/generated repos: a leading '-' would parse
        as an option (e.g. --upload-pack=...), and ext:: runs commands."""
        cleaned = (url or "").strip()
        if not cleaned or cleaned.startswith("-"):
            raise GitError(f"Refusing unsafe git remote URL: {self._mask(cleaned)!r}")
        if self._HELPER_URL_RE.match(cleaned):
            raise GitError(
                f"Refusing git transport-helper remote URL: {self._mask(cleaned)!r}"
            )
        return cleaned

    _URL_CRED_RE = re.compile(r"(https?://)[^/]+@")

    def _strip_url_credentials(self, url: str) -> str:
        """Drop any user:pass@ / token@ part already embedded in an http(s)
        URL — when we inject our own credentials they replace, never join,
        whatever the repo config carried."""
        return self._URL_CRED_RE.sub(r"\1", url)

    def _auth_env(self, url: str) -> Optional[dict]:
        """Subprocess environment carrying the credentials for an http(s)
        remote, or None when there is nothing to inject (non-http(s) remotes,
        or no configured credentials) so the caller inherits the plain env.

        The username/password split mirrors the retired URL forms exactly:
        user+token -> user/token, token-only -> token as the username with an
        empty password (the PAT-as-username form), user-only -> empty
        password so a server that insists on one still fails fast instead of
        hanging on a prompt.
        """
        if not (url.startswith("https://") or url.startswith("http://")):
            return None
        if not self.username and not self.token:
            return None

        env = os.environ.copy()
        # Explicit set, not setdefault: an inherited GIT_ASKPASS (VS Code,
        # ssh-agent wrappers) must not answer for OUR configured identity.
        env["GIT_ASKPASS"] = _ensure_askpass_script()
        if self.username and self.token:
            user, password = self.username, self.token
        elif self.token:
            user, password = self.token, ""
        else:
            user, password = self.username, ""
        env["GENIUS_GIT_ASKPASS_USERNAME"] = user
        env["GENIUS_GIT_ASKPASS_PASSWORD"] = password
        return env

    async def _get_remote_url(self, cwd: Optional[str]) -> Optional[str]:
        # Through _run_git for the timeout backstop + prompt hardening
        # (GIT_TERMINAL_PROMPT=0, closed stdin): a wedged `git remote get-url`
        # (credential helper, lock file) must not hang the caller forever.
        try:
            out = await self._run_git(["remote", "get-url", "origin"], cwd=cwd)
            return out.strip() or None
        except GitError:
            return None

    async def _get_current_branch(self, cwd: Optional[str]) -> Optional[str]:
        try:
            out = await self._run_git(["rev-parse", "--abbrev-ref", "HEAD"], cwd=cwd)
            return out.strip() or None
        except GitError:
            return None

    async def _run_git(
        self, args: List[str], cwd: Optional[str] = None, env: Optional[dict] = None
    ) -> str:
        masked_cmd = "git " + " ".join(self._mask(arg) for arg in args)
        logger.info(f"Running command: {masked_cmd}")

        # Never let git block on an interactive credential/passphrase prompt: a
        # missing or expired token on a push/pull/clone would otherwise hang the
        # coroutine forever. GIT_TERMINAL_PROMPT=0 plus a closed stdin makes auth
        # failures fail fast, and communicate_with_timeout is a hard backstop.
        run_env = dict(env) if env is not None else os.environ.copy()
        run_env.setdefault("GIT_TERMINAL_PROMPT", "0")
        run_env.setdefault("GCM_INTERACTIVE", "never")

        try:
            proc = await asyncio.create_subprocess_exec(
                "git",
                *args,
                stdin=asyncio.subprocess.DEVNULL,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                cwd=cwd,
                env=run_env,
            )
            try:
                stdout_bytes, stderr_bytes = await communicate_with_timeout(
                    proc, timeout=cli_timeout(), cli_name="git"
                )
            except CLITimeoutError as e:
                raise GitError(self._mask(str(e)))
            stdout = stdout_bytes.decode(errors="replace")
            stderr = stderr_bytes.decode(errors="replace")

            if proc.returncode != 0:
                error_msg = f"Git command failed: {masked_cmd}\nExit code: {proc.returncode}\nStdout: {stdout}\nStderr: {stderr}"
                raise GitError(self._mask(error_msg))

            return self._mask(stdout)
        except Exception as e:
            if isinstance(e, GitError):
                raise
            raise GitError(self._mask(f"Failed to execute git command: {str(e)}"))

    async def clone(self, repo_url: str, target_path: str) -> str:
        url = self._validate_remote_url(repo_url)
        env = self._auth_env(url)
        # `--` so a repo_url beginning with `-` can't be parsed as a git option
        # (e.g. --upload-pack=...); it's forced to be positional.
        if env is not None:
            # Credentials ride the askpass env, never argv. `-c
            # credential.helper=` resets the helper list so a system helper
            # (osxkeychain, manager-core) can't answer first with a different
            # identity than the configured one.
            args = [
                "-c",
                "credential.helper=",
                "clone",
                "--",
                self._strip_url_credentials(url),
                target_path,
            ]
        else:
            args = ["clone", "--", url, target_path]
        return await self._run_git(args, env=env)

    async def status(self, cwd: Optional[str] = None) -> str:
        return await self._run_git(["status"], cwd=cwd)

    async def add(self, files: Union[str, List[str]], cwd: Optional[str] = None) -> str:
        # `--` so a filename beginning with `-` isn't parsed as an option flag.
        if isinstance(files, str):
            args = ["add", "--", files]
        else:
            args = ["add", "--"] + list(files)
        return await self._run_git(args, cwd=cwd)

    async def commit(
        self,
        message: str,
        cwd: Optional[str] = None,
        author_name: Optional[str] = None,
        author_email: Optional[str] = None,
    ) -> str:
        env = os.environ.copy()
        if author_name:
            env["GIT_AUTHOR_NAME"] = author_name
            env["GIT_COMMITTER_NAME"] = author_name
        if author_email:
            env["GIT_AUTHOR_EMAIL"] = author_email
            env["GIT_COMMITTER_EMAIL"] = author_email
        return await self._run_git(["commit", "-m", message], cwd=cwd, env=env)

    async def pull(self, cwd: Optional[str] = None) -> str:
        remote_url = await self._get_remote_url(cwd)
        args = ["pull"]
        env = None
        if remote_url:
            # The URL comes back from the repo's own config: validate it and
            # pin it positional with `--` so it can never parse as an option.
            url = self._validate_remote_url(remote_url)
            env = self._auth_env(url)
            if env is not None:
                url = self._strip_url_credentials(url)
                args = ["-c", "credential.helper=", "pull"]
            args.append("--")
            args.append(url)
            branch = await self._get_current_branch(cwd)
            if branch and branch != "HEAD":
                args.append(branch)
        return await self._run_git(args, cwd=cwd, env=env)

    async def push(self, cwd: Optional[str] = None) -> str:
        remote_url = await self._get_remote_url(cwd)
        args = ["push"]
        env = None
        if remote_url:
            # Same hardening as pull: repo-config data stays positional.
            url = self._validate_remote_url(remote_url)
            env = self._auth_env(url)
            if env is not None:
                url = self._strip_url_credentials(url)
                args = ["-c", "credential.helper=", "push"]
            args.append("--")
            args.append(url)
            branch = await self._get_current_branch(cwd)
            if branch and branch != "HEAD":
                args.append(branch)
        return await self._run_git(args, cwd=cwd, env=env)
